name: Full MLflow CI/CD Pipeline for Diabetes Project

on:
  push:
    branches: [ main ]
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLProject

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.21

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set MLflow Tracking URI
        run: echo "MLflow tracking set to local directory (./mlruns)"

      - name: Run mlflow project (Train + Tune)
        run: mlflow run . --env-manager=local

      - name: Upload Model Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/
