name: Full CI/CD Pipeline for Diabetes ML Model with MLflow

on:
  push:
    branches: [ main ]
    paths:
      - 'MLProject/**'
      - 'tests/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-train:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLProject

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          auto-activate-base: false

      - name: Manually create conda environment
        run: |
          conda env create -f MLProject/conda.yaml
          conda activate mlflow-env

      - name: Verify Python & Pip version
        run: |
          python --version
          pip --version

      - name: Install MLflow
        run: pip install mlflow

      - name: Run Unit Tests
        run: pytest ../tests/

      - name: Run Preprocessing & Training with modelling.py
        run: python modelling.py

      - name: Run Hyperparameter Tuning with modelling_tuning.py
        run: python modelling_tuning.py

      - name: Run Training & Tracking with MLflow (optional, jika ada MLproject file)
        if: ${{ hashFiles('MLProject/MLproject') != '' }}
        run: mlflow run . --env-manager=local

      - name: Upload Model Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/
